// Mappa dei logo locali
export const localLogoMap = {
  "hellas verona fc": "logos/Hellas_Verona.png",
  "denmark national football team": "logos/Denmark.png",
  "germany national football team": "logos/Germany.png",
  "stade malherbe caen": "logos/SM_Caen.png",
  "llaneros escuela de futbol": "logos/Llaneros.png",
  "a.c.c.d. mineros de guayana": "logos/Mineros_de_Guayana_logo.png",
  //"Real Madrid C": "logos/Real_Madrid.png",
  "real madrid castilla": "logos/Real_Madrid.png",
  "senegal national football team": "logos/Senegal.png",
  "as lodigiani": "logos/Lodigiani.png",
  "serbia national football team": "logos/Serbia.png",
  "liverpool f.c.": "logos/Liverpool.png",
  //"FC Barcelona C": "logos/Barcelona.png",
  "ghana national football team": "logos/Mali.png",
  "a.c. lumezzane": "logos/Lumezzane.png",
  "faenza calcio": "logos/Faenza.png",
  "lr vicenza": "logos/Vicenza.png",
  "mali national football team": "logos/Mali.jpeg",
  "kenya national football team": "logos/Kenya.png",
  "italy national under-21 football b team": "logos/RapprB.png",
  "america de cali": "logos/Cali.png",
  "ac pavia 1911 ssd": "logos/Pavia.png",
  "asd viareggio calcio": "logos/Viareggio.png",
  "xanthi f.c": "logos/xanthi.png",
  "square united": "logos/Square_UTD.jpeg",
  "saint lucia national football team": "logos/Saint_Lucia.png",
  "valencia cf mestalla": "logos/Valenciacf.png",
};
